name: rpmtw_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  args: ^2.0.0
  byte_size: ^2.0.0-nullsafety.0
  crypto: ^3.0.1
  dart_jsonwebtoken: ^2.4.0
  dbcrypt: ^2.0.0
  dotenv: ^3.0.0
  http: ^0.13.4
  intl: ^0.17.0
  logger: ^1.1.0
  mailer: ^5.0.2
  mongo_dart: ^0.7.4
  path: ^1.8.1
  pub_semver: ^2.1.0
  shelf: ^1.1.0
  shelf_cors_headers: ^0.1.2
  shelf_rate_limiter: ^1.0.1
  shelf_router: ^1.0.0
  socket_io: ^1.0.1

dev_dependencies:
  coverage: ^1.0.3
  lints: ^1.0.0
  socket_io_client: ^1.0.2
  test: ^1.15.0
