name: rpmtw_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com
publish_to: "none"

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"

dependencies:
  args: ^2.0.0
  byte_size: ^2.0.0-nullsafety.0
  crypto: ^3.0.1
  dart_jsonwebtoken: ^2.4.0
  dbcrypt: ^2.0.0
  dotenv: ^3.0.0
  logger: ^1.1.0
  mongo_dart: ^0.7.4
  shelf: ^1.1.0
  shelf_rate_limiter: ^1.0.1
  shelf_router: ^1.0.0
  vm_service: ^7.5.0
  watcher: ^1.0.1

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
