name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Dart
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/dart-sdk
          key: ${{ runner.os }}-dart-2.16.2
      # https://dart.dev/get-dart/archive
      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.16.2
      - name: Build
        run: |
          dart pub get
          dart compile exe bin/main.dart -o bin/main
      - name: Upload file to file.io
        id: upload-file
        uses: heowc/action-file.io@0.2.0
        with:
          file_path: bin/main
          file_basename: main

      - name: Setup on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPMTW_SERVER_SSH_HOST }}
          username: ${{ secrets.RPMTW_SERVER_SSH_USERNAME }}
          key: ${{ secrets.RPMTW_SERVER_SSH_KEY }}
          passphrase: ${{ secrets.RPMTW_SERVER_SSH_PASSPHRASE }}
          script: |
            cd ./RPMTW-Server
            sudo git restore .
            sudo git pull
            sudo docker-compose pull
            sudo docker-compose build --build-arg EXEC_DOWNLOAD_URL=${{ fromJSON(steps.upload-file.outputs.response).link }} --build-arg USE_BINARY=true
            sudo docker-compose down
            sudo docker-compose up -d
