name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: dart compile exe bin/rpmtw_discord_bot.dart -o bin/rpmtw_discord_bot
      - name: Upload file to github artifacts
        id: upload-file
        uses: actions/upload-artifact@v3
        with:
          name: rpmtw_discord_bot
          path: bin/rpmtw_discord_bot
          retention-days: 1
      - name: Build and setup on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPMTW_SERVER_SSH_HOST }}
          username: ${{ secrets.RPMTW_SERVER_SSH_USERNAME }}
          key: ${{ secrets.RPMTW_SERVER_SSH_KEY }}
          passphrase: ${{ secrets.RPMTW_SERVER_SSH_PASSPHRASE }}
          script: |
            cd ./RPMTW-Server
            sudo git pull
            sudo docker-compose pull
            sudo docker-compose build --build-arg EXEC_DOWNLOAD_URL=https://nightly.link/RPMTW/RPMTW-Server/workflows/deploy/main/rpmtw_discord_bot.zip
            sudo docker-compose down
            sudo docker-compose up -d
