name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Dart
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/dart-sdk
          key: ${{ runner.os }}-dart-2.16.1
      # https://dart.dev/get-dart/archive
      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.16.1
      - name: Build
        run: |
          dart pub get
          dart compile exe bin/server.dart -o bin/server
      - name: Upload file to github artifacts
        uses: actions/upload-artifact@v3
        with:
          name: server
          path: bin/server
          retention-days: 1
      - name: Build and setup on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPMTW_SERVER_SSH_HOST }}
          username: ${{ secrets.RPMTW_SERVER_SSH_USERNAME }}
          key: ${{ secrets.RPMTW_SERVER_SSH_KEY }}
          passphrase: ${{ secrets.RPMTW_SERVER_SSH_PASSPHRASE }}
          script: |
            cd ./RPMTW-Server
            sudo git restore .
            sudo git pull
            sudo docker-compose pull
            sudo docker-compose build
            sudo docker-compose down
            sudo docker-compose up -d
